import * as THREE from './three.module.min.js';

const mode = document.body.dataset.mode || 'wind';
const base = document.body.dataset.base || '../';
const pages = {
  performance: {number:'02', name:'Motion stopwatch', title:'Where does the delay live?', intro:'A command is not a visible pose. Follow one long, real G1 session from each instruction through planning, scheduling, and streamed motion. Stop the film at any point and inspect what the server recorded.', question:'Can this laptop sustain responsive motion?', note:'This is one CPU capture on one laptop. Planner time and command-to-scheduled time are different measurements; neither is browser display latency.'},
  styles: {number:'03', name:'Style DNA atlas', title:'Does style survive motion?', intro:'Switch through a long sequence of locomotion styles and watch how the target ghosts, generated body, and root path change. The label is a hypothesis; the motion is the evidence.', question:'Which differences remain visible when direction stays fixed?', note:'This cinematic sequence carries motion context across switches. It is a transition study, not a speed-matched, independently reset ranking of all styles.'},
  targets: {number:'04', name:'Target-pose lab', title:'How much can a target ask?', intro:'Inspect the four actual placed constraints beside the generated body. Then examine controlled boundary-pose interventions to see how a requested end state changes the model’s output.', question:'Where does a plausible request become unreliable?', note:'The stock T0–T3 control only inspects targets. Precomputed counterfactuals here use the separate stateless inference API; no browser slider runs a neural model on GitHub Pages.'},
  wind: {number:'∞', name:'Motion Wind Tunnel', title:'A long-form test of control.', intro:'Walk forward. Move quietly. Limp. Turn 90°. Side-step. Become a zombie. Dance. Reverse. Crawl. Recover. Stop. The motion, targets, and timing all come from one recorded local MotionBricks session.', question:'What did we ask, what did it plan, and what did it actually draw?', note:'This is recorded model output, replayed as an interactive exhibit. GitHub Pages does not execute the neural model.'},
};
const page = pages[mode];
const nav = [
  ['02 · Performance', `${base}projects/02-performance/`, 'performance'],
  ['03 · Styles', `${base}projects/03-style-atlas/`, 'styles'],
  ['04 · Targets', `${base}projects/04-target-lab/`, 'targets'],
  ['Wind Tunnel', `${base}wind-tunnel/`, 'wind'],
];
const formatTime = t => `${Math.floor(t / 60).toString().padStart(2,'0')}:${Math.floor(t % 60).toString().padStart(2,'0')}`;
const fmt = (v, n=1) => Number.isFinite(v) ? Number(v).toFixed(n) : '—';
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

document.querySelector('#app').innerHTML = `
  <div class="shell">
    <header class="topbar"><a class="brand" href="${base}index.html">MotionBricks / Field Lab</a><nav aria-label="Project navigation">${nav.map(([name,url,key])=>`<a href="${url}" ${key===mode?'aria-current="page"':''}>${name}</a>`).join('')}</nav></header>
    <main>
      <section class="intro"><div><div class="kicker">Project ${page.number} · ${page.name} · Real G1 capture</div><h1>${page.title}</h1><p>${page.intro}</p></div><div class="side-note"><b>The question</b>${page.question}</div></section>
      <section aria-label="Interactive motion exhibit"><div class="console"><div class="stage" id="stage"><div class="stage-top"><div class="stage-label"><span class="micro">Command in effect</span><strong id="command">Loading capture…</strong></div><div class="stage-time" id="stage-time">00:00</div></div><div class="stage-bottom"><div class="legend"><span style="--dot:var(--cyan)">Generated G1</span><span style="--dot:var(--amber)">Target pose</span><span style="--dot:var(--rose)">Command change</span></div><div class="stage-label micro" id="pose-count">— poses</div></div></div><aside class="readout" id="readout" aria-label="Motion measurements"></aside></div>
      <div class="transport"><div class="transport-top"><button class="play" id="play" type="button" aria-label="Pause animation">Pause</button><input type="range" id="scrub" min="0" max="1000" value="0" aria-label="Scrub recorded motion"><span class="micro" id="duration">00:00</span></div><div class="time-ends"><span>00:00</span><span id="end-time">00:00</span></div><div class="phase-track" id="phase-track" aria-label="Command sequence"></div><div class="options"><label><input id="targets" type="checkbox" checked> Show target ghost</label><label><input id="follow" type="checkbox" checked> Follow motion</label><button type="button" id="speed" aria-label="Playback speed">1× speed</button><button type="button" id="replay" aria-label="Restart animation">Restart</button><span>Drag the stage to orbit · Scroll to zoom</span></div><div class="phase-labels" id="phase-labels"></div></div></section>
      <section class="below"><div id="project-content"></div><div class="evidence"><span class="kicker">Read the evidence correctly</span><h2>What this exhibit can claim</h2><p>${page.note}</p><p id="capture-summary">Loading the captured measurements.</p><p>The <a href="https://github.com/localai-org/motion-bricks.cpp/tree/2727a456e0a99baf64476496cd58115fef717944">original C++ implementation</a> generated these G1 poses. The project code, reproducible capture script, and data are in the <a href="https://github.com/az9713/motionbricks-projects">MotionBricks projects repository</a>.</p></div></section>
    </main><footer class="footer">MotionBricks field lab · Independent educational experiments · <a href="${base}index.html">All projects</a> · <a href="https://www.youtube.com/watch?v=lj-xPo7ueGA">Starting video</a> · <a href="https://github.com/localai-org/motion-bricks.cpp">Original repo</a></footer>
  </div>`;

const $ = selector => document.querySelector(selector);
const stage = $('#stage');
const canvas = document.createElement('canvas');
canvas.setAttribute('aria-label','Animated 3D G1 skeleton and target pose');
canvas.setAttribute('role','img');
stage.prepend(canvas);
const state = {data:null,time:0,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,speed:1,showTargets:true,follow:true,last:performance.now(),rig:null,ghost:null,targetIndex:-1,phaseIndex:-1,frameIndex:-1,cameraAngle:.68,cameraHeight:.29,cameraDistance:3,drag:false};
const scene = new THREE.Scene();
scene.background = new THREE.Color('#071522');
scene.fog = new THREE.FogExp2('#071522',.028);
const camera = new THREE.PerspectiveCamera(39,1,.08,200);
const renderer = new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio || 1,1.65));
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
scene.add(new THREE.HemisphereLight(0xbceeff,0x203346,2.1));
const lamp = new THREE.DirectionalLight(0xffffff,3.0);lamp.position.set(-3,7,5);scene.add(lamp);
const grid = new THREE.GridHelper(100,100,0x244f63,0x173144);grid.position.y=-.018;scene.add(grid);
const floor = new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshBasicMaterial({color:0x081c28,transparent:true,opacity:.86,depthWrite:false}));floor.rotation.x=-Math.PI/2;floor.position.y=-.032;scene.add(floor);
const halo = new THREE.Mesh(new THREE.TorusGeometry(.58,.009,6,80),new THREE.MeshBasicMaterial({color:0x5de8e5,transparent:true,opacity:.65}));halo.rotation.x=Math.PI/2;scene.add(halo);
const halo2 = new THREE.Mesh(new THREE.TorusGeometry(1.05,.005,4,96),new THREE.MeshBasicMaterial({color:0xffc179,transparent:true,opacity:.38}));halo2.rotation.x=Math.PI/2;scene.add(halo2);
const up = new THREE.Vector3(0,1,0), a = new THREE.Vector3(), b = new THREE.Vector3(), mid = new THREE.Vector3(), qNext = new THREE.Quaternion();
const sphere = new THREE.SphereGeometry(1,10,8);
const bar = new THREE.CylinderGeometry(1,1,1,7);
function makeRig(joints,color,opacity,radius){
  const group=new THREE.Group(), bones=[], markers=[], segments=[];
  const material=new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.1,roughness:.5,transparent:opacity<1,opacity,depthWrite:opacity>.9});
  for(let i=0;i<joints.length;i++){
    const joint=joints[i], bone=new THREE.Bone();
    if(joint.parent>=0){const parent=joints[joint.parent].position;bone.position.set(joint.position[0]-parent[0],joint.position[1]-parent[1],joint.position[2]-parent[2]);bones[joint.parent].add(bone)}
    bones.push(bone);
    const marker=new THREE.Mesh(sphere,material);marker.scale.setScalar(i===0?radius*1.7:radius);markers.push(marker);group.add(marker);
    if(joint.parent>=0){const mesh=new THREE.Mesh(bar,material);group.add(mesh);segments.push({mesh,parent:joint.parent,child:i})}
  }
  scene.add(bones[0],group);
  function update(){bones[0].updateMatrixWorld(true);for(let i=0;i<bones.length;i++)bones[i].getWorldPosition(markers[i].position);for(const seg of segments){a.copy(markers[seg.parent].position);b.copy(markers[seg.child].position);const delta=b.clone().sub(a);seg.mesh.position.copy(mid.copy(a).add(b).multiplyScalar(.5));seg.mesh.quaternion.setFromUnitVectors(up,delta.clone().normalize());seg.mesh.scale.set(radius*.55,delta.length(),radius*.55)}}
  return {group,bones,update,setVisible(v){group.visible=v;bones[0].visible=v}};
}
let trace;
function setTrace(frames){if(trace){scene.remove(trace);trace.geometry.dispose();trace.material.dispose()}const vertices=new Float32Array(frames.length*3);frames.forEach((f,i)=>{vertices[i*3]=f.r[0];vertices[i*3+1]=.035;vertices[i*3+2]=f.r[2]});const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(vertices,3));geometry.setDrawRange(0,0);trace=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:0x5de8e5,transparent:true,opacity:.82}));scene.add(trace)}
function frameAt(t){const frames=state.data.frames;let lo=0,hi=frames.length-1;while(lo<hi){const m=(lo+hi+1)>>1;if(frames[m].t<=t)lo=m;else hi=m-1}return lo}
function centerCamera(){if(!state.data)return;const root=state.data.frames[frameAt(state.time)].r;camera.position.set(root[0]+Math.sin(state.cameraAngle)*state.cameraDistance,root[1]+.65+state.cameraDistance*state.cameraHeight,root[2]+Math.cos(state.cameraAngle)*state.cameraDistance);camera.lookAt(root[0],root[1]-.2,root[2])}
function targetAt(t){const events=state.data.targets;let lo=0,hi=events.length-1,found=-1;while(lo<=hi){const m=(lo+hi)>>1;if((events[m].t??events[m].t_wall*state.data.summary.sim_seconds/state.data.summary.wall_seconds)<=t){found=m;lo=m+1}else hi=m-1}return found}
function renderPose(){if(!state.data)return;const frames=state.data.frames,i=frameAt(state.time),f=frames[i],n=frames[Math.min(i+1,frames.length-1)],fraction=n.t>f.t?THREE.MathUtils.clamp((state.time-f.t)/(n.t-f.t),0,1):0;const rig=state.rig;
  rig.bones[0].position.set(f.r[0],f.r[1],f.r[2]).lerp(new THREE.Vector3(...n.r),fraction);
  for(let j=0;j<34;j++)rig.bones[j].quaternion.fromArray(f.q,j*4).slerp(qNext.fromArray(n.q,j*4),fraction);
  rig.update();trace.geometry.setDrawRange(0,i+1);state.frameIndex=i;
  const ti=targetAt(state.time);if(ti!==state.targetIndex){state.targetIndex=ti;if(ti>=0){const e=state.data.targets[ti],g=state.ghost;if(e.roots.length===12&&e.rotations.length===544){g.bones[0].position.fromArray(e.roots,9);for(let j=0;j<34;j++)g.bones[j].quaternion.fromArray(e.rotations,(3*34+j)*4);g.update();g.setVisible(state.showTargets)}else g.setVisible(false)}}
  const phase=state.data.phases.reduce((index,p,k)=>p.t<=state.time?k:index,0);if(phase!==state.phaseIndex){state.phaseIndex=phase;$('#command').textContent=state.data.phases[phase].label;document.querySelectorAll('.phase-labels button,.phase-track button').forEach(el=>el.classList.toggle('active',Number(el.dataset.phase)===phase));updateReadout()}
  $('#stage-time').textContent=formatTime(state.time);$('#pose-count').textContent=`Pose ${i+1} / ${frames.length}`;$('#duration').textContent=formatTime(state.time);$('#scrub').value=Math.round(1000*state.time/state.data.summary.sim_seconds);
  const root=rig.bones[0].position;halo.position.set(root.x,.04,root.z);halo2.position.set(root.x,.04,root.z);halo.rotation.z=state.time*.2;halo2.rotation.z=-state.time*.1;
  if(state.follow){const az=state.cameraAngle,dist=state.cameraDistance,elev=state.cameraHeight;camera.position.lerp(new THREE.Vector3(root.x+Math.sin(az)*dist,root.y+.65+dist*elev,root.z+Math.cos(az)*dist),.12);camera.lookAt(root.x,root.y-.2,root.z)}
  updateDynamic();
}
function updateDynamic(){if(!state.data)return;const f=state.data.frames[state.frameIndex];if(!f)return;const status=$('#current-style');if(status)status.textContent=f.style.replaceAll('_',' ');const slow=$('#slow-ticks');if(slow)slow.textContent=String(f.slow);const seen=$('#current-target');if(seen)seen.textContent=state.targetIndex>=0?state.data.targets[state.targetIndex].style.replaceAll('_',' '):'waiting';const phase=$('#current-command');if(phase)phase.textContent=state.data.phases[state.phaseIndex]?.label||'—'}
function updateReadout(){if(!state.data)return;const phases=state.data.phases,phase=phases[Math.max(0,state.phaseIndex)];const acks=state.data.acks.filter(x=>x.state==='scheduled'&&Number.isFinite(x.planner_ms));const values=acks.map(x=>x.planner_ms).sort((a,b)=>a-b);const median=values.length?values[Math.floor(values.length/2)]:NaN;let html='';
  if(mode==='performance'){const ack=acks.find(x=>x.seq===phase.seq);const latency=ack&&Number.isFinite(phase.request_wall)?(ack.t_wall-phase.request_wall)*1000:NaN;html=`<div><span class="micro">Current instruction</span><div class="readout-value" id="current-command">${escape(phase.label)}</div><small>Command recorded at ${fmt(phase.t)} seconds of simulation.</small></div><div class="divider"></div><div><span class="micro">Planner time · this command</span><div class="readout-value amber">${ack?fmt(ack.planner_ms,0):'—'}<small style="display:inline;color:inherit"> ms</small></div><small>Inside the native planning call, where reported.</small></div><div><span class="micro">Command → scheduled ack</span><div class="readout-value">${fmt(latency,0)}<small style="display:inline;color:inherit"> ms</small></div><small>Includes waiting and server scheduling; excludes browser display.</small></div><div class="divider"></div><div><span class="micro">Sample median planner time</span><div class="readout-value">${fmt(median,0)}<small style="display:inline;color:inherit"> ms</small></div><small>${acks.length} scheduled commands in this session.</small></div>`}
  else if(mode==='styles'){html=`<div><span class="micro">Style now on screen</span><div class="readout-value" id="current-style">${escape(phase.style.replaceAll('_',' '))}</div><small>Style names are asset labels, not verified movement classifiers.</small></div><div class="divider"></div><div><span class="micro">Commanded movement</span><div class="readout-value amber">[${phase.move.join(', ')}]</div><small>Horizontal X/Z direction from the recorded command.</small></div><div><span class="micro">Observed styles</span><div class="readout-value">${state.data.summary.styles_observed.length}</div><small>Distinct styles in this cinematic transition run.</small></div>`}
  else if(mode==='targets'){html=`<div><span class="micro">Controller target</span><div class="readout-value amber" id="current-target">${escape(phase.style.replaceAll('_',' '))}</div><small>Amber ghost = fourth pose of the latest four-frame target event.</small></div><div class="divider"></div><div><span class="micro">Target sets captured</span><div class="readout-value">${state.data.summary.target_events}</div><small>These are real constraints published by the server.</small></div><div><span class="micro">Question</span><p>After a sudden turn, does the generated body follow the target immediately or transition over several frames?</p></div>`}
  else {html=`<div><span class="micro">Command</span><div class="readout-value" id="current-command">${escape(phase.label)}</div><small>Phase ${state.phaseIndex+1} of ${phases.length}</small></div><div class="divider"></div><div><span class="micro">Motion style</span><div class="readout-value amber" id="current-style">${escape(phase.style.replaceAll('_',' '))}</div><small>Watch the amber target change before judging the cyan output.</small></div><div><span class="micro">Server slow ticks</span><div class="readout-value rose" id="slow-ticks">0</div><small>Cumulative scheduler counter in the recorded stream.</small></div><div class="divider"></div><div><span class="micro">Planned command changes</span><div class="readout-value">${state.data.summary.scheduled_plans}</div><small>One long continuous run; no invented motion between segments.</small></div>`}
  $('#readout').innerHTML=html;
}
function makeContent(){const data=state.data,summary=data.summary,planned=data.acks.filter(x=>x.state==='scheduled'&&Number.isFinite(x.planner_ms));const avg=planned.reduce((sum,x)=>sum+x.planner_ms,0)/(planned.length||1);const stats=`<div class="data-list"><div><b>${fmt(summary.sim_seconds,0)} s</b><span>recorded simulation</span></div><div><b>${summary.sampled_frames.toLocaleString()}</b><span>real sampled poses</span></div><div><b>${summary.target_events}</b><span>target events</span></div></div>`;
  $('#capture-summary').textContent=`Capture: ${fmt(summary.sim_seconds,1)} seconds of G1 simulation, ${summary.sampled_frames} sampled model poses, ${summary.target_events} target events, ${summary.scheduled_plans} scheduled command changes. CPU backend; no physical simulation or GPU claim.`;
  if(mode==='performance'){$('#project-content').innerHTML=`<span class="kicker">Project 2 / The measurement</span><h2>See the gap between computation and response.</h2><p>Each amber bar is a planner duration reported by the server for a scheduled command. The readout also compares the wall-clock interval from sending that command to receiving its scheduled acknowledgment. The difference includes scheduling and waiting; it is not a measured browser presentation time.</p>${stats}<div class="chart" aria-label="Planner duration bars">${planned.map((x,i)=>`<div style="--h:${Math.max(4,Math.min(100,x.planner_ms/Math.max(...planned.map(y=>y.planner_ms))*100))}%" title="Plan ${i+1}: ${fmt(x.planner_ms,0)} ms"></div>`).join('')}</div><p>Mean planner duration across these ${planned.length} scheduled commands: <strong>${fmt(avg,0)} ms</strong>. A future matched CPU/Vulkan run is required before claiming a GPU advantage on this 4 GB card.</p>`}
  else if(mode==='styles'){const unique=[...new Set(data.phases.map(p=>p.style))];$('#project-content').innerHTML=`<span class="kicker">Project 3 / Style DNA</span><h2>Use the style names as hypotheses.</h2><p>Pick a style to jump to its first appearance. Compare the amber constraints, body height, arm pose, and path. This recording carries context across transitions: a later style inherits what the character was doing before the switch.</p>${stats}<div class="style-grid">${unique.map(style=>{const p=data.phases.find(x=>x.style===style);return `<button type="button" data-seek="${p.t}" data-style="${escape(style)}">${escape(style.replaceAll('_',' '))}<small>${escape(p.label)} · ${fmt(p.t)} s</small></button>`}).join('')}</div><p>For a causal style comparison, each style must also be tested from the same initial context, direction, nominal speed, and seed. The atlas is a transition exhibit, not that controlled benchmark.</p>`}
  else if(mode==='targets'){$('#project-content').innerHTML=`<span class="kicker">Project 4 / Inspect before intervening</span><h2>Targets are requests, not pose pins.</h2><p>The amber skeleton is T3, the last of four consecutive 30 FPS target frames. It is the actual latest controller constraint recorded by the local server. Toggle its visibility, then inspect a turn or a stop frame by frame.</p>${stats}<div class="target-controls"><button type="button" data-seek="19">Turn onset <small>Injured walk → 90° right command</small></button><button type="button" data-seek="24">Side-step onset <small>Direction and facing separate</small></button><button type="button" data-seek="54">Stop onset <small>Target path contracts</small></button></div><p>A separate counterfactual panel below will compare real stateless inference runs from altered boundary poses. The ordinary viewer does not edit targets.</p><div id="counterfactual"></div>`}
  else $('#project-content').innerHTML=`<span class="kicker">The experiment / One uninterrupted scene</span><h2>A minute of decisions, not a montage.</h2><p>The timeline below the stage is the command script. Every cyan pose is a sampled output of the local G1 model; the amber ghost is a target event from its controller. Pause before a switch and make a prediction. Then replay the next seconds to see whether the body and trajectory follow the request.</p>${stats}<p>Look especially at the injured 90° turn, the contrast between sideways travel and facing, the transition into crawling, and how the character stops. The wind tunnel unites the stopwatch, style atlas, and target inspector, while keeping their measurement limits visible.</p>`;
  if(mode==='styles')document.querySelectorAll('.style-grid button').forEach(button=>{const p=data.phases.find(x=>x.t===Number(button.dataset.seek));const segment=data.frames.filter(f=>f.t>=p.t+1&&f.t<=p.t+p.duration&&f.style===p.style);if(segment.length>2){let travel=0;for(let i=1;i<segment.length;i++)travel+=Math.hypot(segment[i].r[0]-segment[i-1].r[0],segment[i].r[2]-segment[i-1].r[2]);const speed=travel/(segment.at(-1).t-segment[0].t);const height=segment.reduce((sum,f)=>sum+f.r[1],0)/segment.length;button.insertAdjacentHTML('beforeend',`<small>Late-phase root ${fmt(speed,2)} m/s · pelvis ${fmt(height,2)} m</small>`)}});
  document.querySelectorAll('[data-seek]').forEach(button=>button.addEventListener('click',()=>{state.time=Number(button.dataset.seek);state.playing=false;$('#play').textContent='Play';$('#play').setAttribute('aria-label','Play animation');centerCamera();renderPose();document.querySelectorAll('.style-grid button').forEach(b=>b.classList.toggle('active',b===button))}));
}
function phaseControls(){const phases=state.data.phases,total=state.data.summary.sim_seconds;$('#phase-track').innerHTML=phases.map((p,i)=>`<button type="button" data-phase="${i}" style="flex:${p.duration}" aria-label="Jump to ${escape(p.label)} at ${formatTime(p.t)}"><span></span></button>`).join('');$('#phase-labels').innerHTML=phases.map((p,i)=>`<button type="button" data-phase="${i}">${escape(p.label)}</button>`).join('');document.querySelectorAll('[data-phase]').forEach(button=>button.addEventListener('click',()=>{state.time=phases[Number(button.dataset.phase)].t;centerCamera();renderPose()}));$('#scrub').oninput=e=>{state.time=Number(e.target.value)/1000*total;centerCamera();renderPose()};$('#end-time').textContent=formatTime(total)}
function selectDataset(data){state.data=data;state.time=0;state.frameIndex=-1;state.phaseIndex=-1;state.targetIndex=-1;state.playing=true;$('#play').textContent='Pause';$('#play').setAttribute('aria-label','Pause animation');state.ghost.setVisible(false);setTrace(data.frames);phaseControls();updateReadout();centerCamera();renderPose()}
function variantDataset(variant,source){const count=variant.frames,frames=Array.from({length:count},(_,i)=>({t:i/30,tick:i,r:variant.roots.slice(i*3,i*3+3),q:variant.rotations.slice(i*136,i*136+136),style:'stateless inference',revision:1,slow:0}));const requested=source.roots.map((v,i)=>v+(i%3===0?variant.dx:i%3===2?variant.dz:0));return {schema:'motionbricks-capture-v1',joints:state.storyData.joints,frames,phases:[{label:variant.label,style:'stateless inference',move:[variant.dx,variant.dz],facing:[0,1],t:0,duration:(count-1)/30,seq:1}],targets:[{t:0,style:'requested endpoint',revision:1,roots:requested,rotations:source.rotations}],acks:[],summary:{sim_seconds:(count-1)/30,wall_seconds:(count-1)/30,sampled_frames:count,styles_observed:['stateless inference'],target_events:1,scheduled_plans:0}}}
async function loadCounterfactual(){const panel=$('#counterfactual');if(!panel)return;try{const response=await fetch(`${base}shared/counterfactual.json`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json();if(result.schema!=='motionbricks-counterfactual-v1'||result.variants.length<4)throw new Error('Invalid inference dataset');panel.innerHTML=`<h3>Four real counterfactuals</h3><p>Same four source poses, same target joint rotations, same 40-frame duration and seed ${result.seed}. Only the target root position moves sideways. Choose a request to replay the model's resulting 40 frames; use the amber ghost to compare its requested ending.</p><div class="target-controls">${result.variants.map((v,i)=>`<button type="button" data-variant="${i}">${escape(v.label)} <small>Target X +${fmt(v.dx,2)} m · end-position error ${fmt(v.end_error_m,3)} m</small></button>`).join('')}<button type="button" id="return-story">Return to 59-second sequence <small>Inspect controller targets and transitions again</small></button></div><p id="variant-status">The source motion is a real four-frame G1 target event from the recorded walk. These experiments use the separate stateless inference API. They test target response, not physics or generalization to arbitrary poses.</p>`;panel.querySelectorAll('[data-variant]').forEach(button=>button.addEventListener('click',()=>{const v=result.variants[Number(button.dataset.variant)];selectDataset(variantDataset(v,result.source_poses));panel.querySelectorAll('[data-variant]').forEach(b=>b.classList.toggle('active',b===button));$('#variant-status').textContent=`${v.label}: requested end root ${v.requested_last_root.map(x=>fmt(x,2)).join(', ')} m; generated end root ${v.generated_last_root.map(x=>fmt(x,2)).join(', ')} m; positional difference ${fmt(v.end_error_m,3)} m. A small endpoint error does not prove realistic intermediate motion.`;$('#capture-summary').textContent=`Stateless inference: ${v.frames} generated frames at 30 FPS, seed ${result.seed}, requested lateral shift ${fmt(v.dx,2)} m. The full 59-second controller capture remains available with Return.`}));$('#return-story').addEventListener('click',()=>{selectDataset(state.storyData);$('#capture-summary').textContent=`Capture: ${fmt(state.storyData.summary.sim_seconds,1)} seconds of G1 simulation, ${state.storyData.summary.sampled_frames} sampled model poses, ${state.storyData.summary.target_events} target events, ${state.storyData.summary.scheduled_plans} scheduled command changes. CPU backend.`;panel.querySelectorAll('[data-variant]').forEach(b=>b.classList.remove('active'));$('#variant-status').textContent='Back in the one-minute controller sequence.'})}catch(error){panel.innerHTML=`<p class="error">Could not load counterfactual inference results: ${escape(error.message)}</p>`}}
$('#play').addEventListener('click',()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'Pause':'Play';$('#play').setAttribute('aria-label',`${state.playing?'Pause':'Play'} animation`)});
$('#targets').addEventListener('change',e=>{state.showTargets=e.target.checked;if(state.ghost)state.ghost.setVisible(state.showTargets&&state.targetIndex>=0)});
$('#follow').addEventListener('change',e=>{state.follow=e.target.checked});
$('#replay').addEventListener('click',()=>{state.time=0;state.playing=true;$('#play').textContent='Pause';$('#play').setAttribute('aria-label','Pause animation');centerCamera();renderPose()});
$('#speed').addEventListener('click',()=>{state.speed=state.speed===1?.5:state.speed===.5?1.5:1;$('#speed').textContent=`${state.speed}× speed`});
canvas.addEventListener('pointerdown',e=>{state.drag=true;canvas.setPointerCapture(e.pointerId);state.lastX=e.clientX;state.lastY=e.clientY});
canvas.addEventListener('pointermove',e=>{if(!state.drag)return;state.cameraAngle+=(e.clientX-state.lastX)*.006;state.cameraHeight=THREE.MathUtils.clamp(state.cameraHeight+(e.clientY-state.lastY)*.004,.05,.8);state.lastX=e.clientX;state.lastY=e.clientY});
canvas.addEventListener('pointerup',()=>{state.drag=false});canvas.addEventListener('wheel',e=>{e.preventDefault();state.cameraDistance=THREE.MathUtils.clamp(state.cameraDistance+Math.sign(e.deltaY)*.35,2.4,11)},{passive:false});
function animate(now){requestAnimationFrame(animate);const dt=Math.min(.08,(now-state.last)/1000);state.last=now;if(state.data){if(state.playing){state.time+=dt*state.speed;if(state.time>=state.data.summary.sim_seconds)state.time=0}renderPose()}const w=stage.clientWidth,h=stage.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio())){renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}renderer.render(scene,camera)}requestAnimationFrame(animate);
try{const captureFile=mode==='styles'?'atlas.json':'story.json';const response=await fetch(`${base}shared/${captureFile}`,{cache:'no-store'});if(!response.ok)throw new Error(`capture HTTP ${response.status}`);const data=await response.json();if(data.schema!=='motionbricks-capture-v1'||data.joints.length!==34||data.frames.length<1000)throw new Error('Invalid or incomplete G1 capture');state.data=data;state.storyData=data;state.rig=makeRig(data.joints,0x5de8e5,1,.042);state.ghost=makeRig(data.joints,0xffb36b,.65,.03);state.ghost.setVisible(false);setTrace(data.frames);phaseControls();makeContent();state.time=0;centerCamera();renderPose();$('#play').textContent=state.playing?'Pause':'Play';$('#play').setAttribute('aria-label',`${state.playing?'Pause':'Play'} animation`);if(mode==='targets')await loadCounterfactual();document.documentElement.dataset.ready='true'}catch(error){stage.insertAdjacentHTML('beforeend',`<div class="error">Could not load verified motion capture: ${escape(error.message)}</div>`);console.error(error)}
